name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Run every 5 hours

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # ... [previous steps remain unchanged]

      - name: Run Spigot and cloudflared with auto-restart and workflow recreation
        if: "!contains(github.event.head_commit.message, 'Auto commit every 30 seconds')"
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
          CF_TUNNEL_CERT: ${{secrets.CF_CERT}}
          CF_TUNNEL_UUID: ${{secrets.CF_TUNNEL_UUID_1}}
          CF_TUNNEL_UUID_CONTENT: ${{secrets.CF_TUNNEL_UUID_CONTENT}}
        run: |
          # ... [previous function definitions remain unchanged]

          cancel_old_workflow_runs() {
            current_run_id=$GITHUB_RUN_ID
            workflow_runs=$(curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
              "https://api.github.com/repos/${REPO}/actions/runs?branch=main&status=in_progress")
            
            echo "$workflow_runs" | jq -r ".workflow_runs[] | select(.id != $current_run_id) | .id" | while read -r run_id; do
              echo "Cancelling workflow run $run_id"
              curl -s -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
                "https://api.github.com/repos/${REPO}/actions/runs/$run_id/cancel"
            done
          }

          start_spigot
          start_cloudflared
          
          START_TIME=$(date +%s)
          
          (sleep 30 && cancel_old_workflow_runs) &
          
          while true; do
            if ! commit_and_push; then
                echo "Commit and push failed, continuing without stopping the workflow"
            fi
            delete_auto_commit_workflows
            
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            
            if ! kill -0 $SPIGOT_PID 2>/dev/null; then
              echo "Spigot process has stopped. Restarting Spigot..."
              start_spigot
            fi

            if ! kill -0 $CLOUDFLARED_PID 2>/dev/null || [ $ELAPSED_TIME -ge 18000 ]; then
              if ! kill -0 $CLOUDFLARED_PID 2>/dev/null; then
                echo "Cloudflare Tunnel process has stopped."
              else
                echo "Workflow has been running for 5 hours."
              fi
              echo "Creating new workflow run and exiting current one."
              create_new_workflow_run
              exit 0
            fi
            
            sleep 30
          done
